<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <!-- <script src="Promise.js"></script> -->
  <script src="Promise_class.js"></script>

  <!-- <script>
    /*
    测试.then()和.catch()
    Promise.resolve(value)
    value是将被Promise对象解析的参数，可以是一个成功/失败的Promise对象或值
    Promise.reject(reason)
    reason表示被拒绝的原因，不能是Promise对象
    */
    const p = new Promise((resolve, reject) => {
      setTimeout(() => {
        //resolve(1)
        reject(2)
        //console.log('reject()改变状态之后')
      }, 100)
    }).then(
      value => {
        console.log('onResolved1()', value)
      },
      reason => {
        console.log('onRejected1()', reason)
        //return 3
        //throw 4
        return new Promise((resolve, reject) => {reject(5)})
      }
    ).then(
      value => {
        console.log('onResolved2()', value)
      },
      reason => {
        console.log('onRejected2()', reason)
        throw 6
      }
    ).catch(
      reason => {
        console.log('onRejected3()', reason)
        return new Promise(() => {}) // 中断promise链
      }
    ).then(
      value => {
        console.log('onResolved4()', value)
      },
      reason => {
        console.log('onRejected4()', reason)
        throw 6
      }
    )
  </script> -->
  <!-- <script>
    /*
    测试Promise.resolve(value)和Promise.reject(reason)
    语法
    1.Promise.resolve(value)
    value是将被Promise对象解析的参数，可以是一个成功/失败的Promise对象或值
    2.Promise.reject(reason)
    reason表示被拒绝的原因，不能是Promise对象
    */
    const p1 = Promise.resolve(2) // 如果是一般值，p1成功，value就是这个值
    const p2 = Promise.resolve(Promise.resolve(3)) // 如果是成功的promise，p2成功，value就是这个promise的value
    const p3 = Promise.resolve(Promise.reject(4)) // 如果是失败的promise，p3失败，reason就是这个promise的reason
    p1.then(value => {
      console.log('p1', value)
    })
    p2.then(value => {
      console.log('p2', value)
    })
    p3.catch(reason => {
      console.log('p3', reason)
    })
  </script> -->
  <script>
    /*
    测试Promise.all(value)和Promise.race(reason)
    语法
    1.Promise.resolve(value)
    value是将被Promise对象解析的参数，可以是一个成功/失败的Promise对象或值
    2.Promise.reject(reason)
    reason表示被拒绝的原因，不能是Promise对象
    */
    const p1 = Promise.resolve(2) // 如果是一般值，p1成功，value就是这个值
    const p2 = Promise.resolve(Promise.resolve(3)) // 如果是成功的promise，p2成功，value就是这个promise的value
    const p3 = Promise.resolve(Promise.reject(4)) // 如果是失败的promise，p3失败，reason就是这个promise的reason(只返回第一个失败的reason)
    /*const p4 = new Promise((resolve, reject) =>
      setTimeout(() => {
        resolve(5)
      }, 1000)
    )*/
    const p4 = Promise.resolveDelay(5, 1000) // 新的写法
    const p5 = Promise.reject(6)
    const pAll = Promise.all([p4, 7, p1, p2])
    pAll.then(
      value => {
        console.log('all onResolved()', value)
      },
      reason => {
        console.log('all onRejected()', reason)
      }
    )
    /*const pRace = Promise.race([p4, 7, p1, p2])
    pRace.then(
      value => {
        console.log('race onResolved()', value)
      },
      reason => {
        console.log('race onRejected()', reason)
      }
    )*/

    /*
    测试自定义的两个函数
    Promise.resolveDelay()和Promise.rejectDelay()
    */
    const p6 = Promise.resolveDelay(66, 2000)
    const p7 = Promise.rejectDelay(77, 3000)
    p6.then(value => {
      console.log('p6', value)
    })
    p7.catch(reason => {
      console.log('p7', reason)
    })
  </script>
</body>

</html>